substitutions:
  _GCS_CACHE_BUCKET: salus-cache
  _SALUS_PROJECT: salus-template

steps:

  # Pull down settings file for Artifactory settings
  - id: GET_SETTINGS
    name: 'gcr.io/cloud-builders/gsutil'
    waitFor: ['-']
    args: ['cp', 'gs://salus-mavenrepository/m2-settings.xml', '.mvn/settings.xml']

  # Load the cached files from GCS if they exist.
  - id: PULL_DOWN_CACHE
    waitFor: ['-']
    name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
    - -c
    - |
      (
        gsutil cp gs://${_GCS_CACHE_BUCKET}/${_SALUS_PROJECT}-m2-cache.tar.gz /tmp/m2-cache.tar.gz &&
        tar -xzf /tmp/m2-cache.tar.gz
      ) || echo 'Cache not found'
    volumes:
    - name: user.home
      path: /root

  - id: VERIFY
    name: 'gcr.io/cloud-builders/mvn'
    args: ['verify', '-s', '.mvn/settings.xml']
    volumes:
    - name: user.home
      path: /root

  # Saves the files to the GCS cache.
  - id: PUSH_UP_CACHE
    waitFor:
    - VERIFY
    name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    # Caches the local Maven repository.
    args:
    - -c
    - |
      set -ex
      tar -czf /tmp/m2-cache.tar.gz .m2 &&
      gsutil cp /tmp/m2-cache.tar.gz gs://${_GCS_CACHE_BUCKET}/${_SALUS_PROJECT}-m2-cache.tar.gz
    volumes:
    - name: user.home
      path: /root
